### ISSUE TITLE
Question: Parsing mails from SMTP server // doubled dots

### ISSUE THREAD

**Issue by TomFreudenberg** [mikel/mail#1279]
Hi,

I am writing the MidiSmtpServer Class and wondering what component should remove the doubled dot corresponding rfc http://tools.ietf.org/html/rfc5321#section-4.5.2

While mail component WILL double a single dot when sending via SMTP it WON'T remove any first char (extra) dot when parsing `Mail.read_from_string(data)`.

My question is now: is this correct and do I have to remove the doubled dots while receiving the incoming SMTP data during DATA command?

Thanks for some feedback
Tom

**Comment by jeremy** [comment]
The SMTP protocol handler (MidiSmtpServer) is responsible for dot stuffing and unstuffing. Mail only does dot stuffing to work around a Ruby bug (https://bugs.ruby-lang.org/issues/9627). So, yes, you need to handle this in response to DATA.

**Comment by TomFreudenberg** [comment]
Thanks @jeremy for your response.

**Comment by dlouzan** [comment]
@TomFreudenberg Thanks for the answer! Unless I'm missing anything, I don't see how this process is "reversable"; if my input email had a line with a double-dot, wouldn't it be modified by the SMTP server by removing the first dot? There's no way to differentiate an "intended user sequence" from "dot stuffing handling".

This problem is really relevant when using email signatures as with S/MIME; there's multiple modes, but one of them is calculating the signature and attaching it together with the original unencrypted email in a multipart email. If for any reason any of the intermediate processors modifies the original input part with the dot-stuffing handling, the signature will not match anymore. The only way I could find for avoiding this issue was to forbid the *single-dot-in-a-line* sequence completely in the input, which can be achieved with Q-P.

**Comment by TomFreudenberg** [comment]
Hi Diego @dlouzan 

as far as I can see that should not touch the process of S/MIME handling. In my point of view it is a sending and receiving protocol between a SMTP client and a MTA.

That should mean that any processing of a mail (including signatures) should have been done before `send!` is used.

While sending the stream, any starting '.' is replaced as '..'.

The MTA will remove any first '.' on receiving.

So the message source on client side and on MTA should be the same.

**Comment by dlouzan** [comment]
@TomFreudenberg That's true, but not was I was experiencing with the mail gem on 2.7.1, we did have double-dots on the output email under some circumstances. I see that 2.8.1 has refactored the dot stuffing handling and also removed some special handling, so perhaps this is a solved issue now. Will give it a try, thanks for the input again!

**Comment by dlouzan** [comment]
@TomFreudenberg Indeed the new version that removes the special handling of dot stuffing for older Ruby versions does work properly, I just checked locally. Thanks again for your input.
