### ISSUE TITLE
:sendmail delivery method is broken in Rails

### ISSUE THREAD

**Issue by PeterMozesMerl** [mikel/mail#1321]
I tried to switch from :smtp to :sendmail delivery in my Rails apps due to performance. I noticed that ActionMailer didn’t raise an exception on failure even when the sendmail/exim binary was missing. 

[y-yagi](/y-yagi) wrote that there was a fix. Unfortunately, it is not merged to any stable release. I tried to use the last ref from master (ff17438). I couldn’t send the email at all.

In its current form, the :sendmail delivery from Rails is broken.

https://github.com/rails/rails/issues/35330

**Comment by jeremy** [comment]
That must have been confusing. You'd expect "raise on errors" to mean "shows me the incorrect configuration issue I just had to chase down," but it doesn't. One thing is communicated, but the another thing is implemented!

To unbreak :sendmail delivery, correct your configuration. Note that Rails `raise_delivery_errors` won't raise any other delivery errors, so you may have issues troubleshooting other configuration with your local mail transfer agent. Once the message is queued for delivery, you'll need to inspect logs for evidence of errors, as no exception will be raised.

When Mail 2.8 is released, #1149 will be included to raise on non-zero exitstatus. That's a breaking change, so it's destined for the next minor release rather than backporting to stable releases.

**Comment by PeterMozesMerl** [comment]
When software tries to do its primary task by calling an executable, and it swallows the non-standard exit status or the fact that the binary is missing, it’s broken. It says the mail was delivered when it couldn’t even execute the binary that was supposed to deliver it.

It’s not clear to me what you mean with the broken configuration. I set the executable’s path to 'i/excel/in/hiding'. Do you believe I thought it was the path of the exim binary?

It’s called testing.

That binary has a different location on Linux, FreeBSD, and MacOS. Besides, there can be many other reasons for non-zero exit status that could happen.

I don’t expect anyone to fix it fast. I understand that it’s a lot of work to do it. But until it’s fixed, this feature shouldn’t be advertised because it’s not stable. 

Over the years, I didn’t experience anything similar to this when it’s used with SMTP. It was always reliable.
