### ISSUE TITLE
Feature: add `offset: ` option to `Mail.find` to help e.g. with pagination

### ISSUE THREAD

**Issue by fwolfst** [mikel/mail#1368]
With `Mail.find` (and `Mail.last`, `Mail.first`) you can specify the numbers of mails you want to fetch.
Afaiu all message UIDs are fetched anyway (in the IMAP case https://github.com/mikel/mail/blob/fb53fb369eb2bf0494ac70675970c90cdcc3f495/lib/mail/network/retriever_methods/imap.rb#L78) .

For a webmail client without local storage and probably many other use cases having an additional option (`offset`?) to `#find` would be great; this would allow for pagination.

**Comment by jeremy** [comment]
Agreed in principle. You're expected to use `:keys` to limit the IMAP uid search, but that's a pretty leaky abstraction when paired with `#first/last` which don't suggest pulling back all UIDs but only fetching the message for the first/last one.

That said, this is the way the IMAP protocol works. We'd probably be better off exposing that more clearly rather than using a conceptually-mismatched offset/limit pagination API.  [RFC 4549](https://tools.ietf.org/html/rfc4549) offers strong guidance for the webmail client synchronization case.
