### ISSUE TITLE
Wrong encoding with Content-transfer-encoding: 8bit

### ISSUE THREAD

**Issue by aleshgo** [mikel/mail#845]
hello,

my environment: 
ruby: 2.2.0
mail: 2.6.3

When I parse a mail that contain:

Content-type: text/plain; charset=windows-1251
Content-transfer-encoding: 8bit

and I get a subject and a body field with Encoding: ASCII-8BIT, but it should be Encoding: CP-1251

**Comment by bf4** [comment]
Would you write a failing test for this?  Thanks.

**Comment by aleshgo** [comment]
I'm newbie in ruby but if it helps I have added some tests:
https://github.com/aleshgo/mail/commit/7c45dc48a84cea836b886b005b5b416d3ab4c956

**Comment by afair** [comment]
Hi! I just looked at the code. It seems your email message in message_content is invalid, so wouldn't produce valid results from invalid input. :-( 

SMTP is a 7-bit (ASCII) protocol, and headers that contain any 8+bit words (including window-1251, and even UTF-8 character sets) should be "mime header encoded"  (see RFC2047). Otherwise, any code interpreting your data would have no idea which encoding you are using.

Since the encoding of the data in the header is never defined in email/MIME headers, it must be encoded with the 

    Subject: =?windows-1251?q?...?=

format (with the "..." containing the quoted-printable representation of the data--or with "b" and the base64 representation).  Otherwise, the software has no idea of your encodings, whether iso-88959-*, another 8-bit encoding scheme, or UTF-8 which could span multiple bytes for a character (grapheme).

Your Content-Type header applies only to the body, not the headers. Data for header fields must be mime header encoded. As for the body, it appears to be okay (though I can't confirm the representation)

    mail.encoding #=> #<Encoding:Windows-1251>

Encoding is hard :-( Ruby string encodings are tricky, and encoding in email is harder :-( I've been there, the problem exists in any language and ecosystem. :-(
