### ISSUE TITLE
warning: regexp match /.../n against UTF-8 string

### ISSUE THREAD

**Issue by sk-** [mikel/mail#899]
When parsing my emails I'm getting some warnings

```
/Users/skreft/.rvm/gems/ruby-2.2.1/gems/mail-2.6.3/lib/mail/utilities.rb:57: warning: regexp match /.../n against to UTF-8 string
```

**Comment by doooby** [comment]
Hi there. Is there any reason for using `/.../n` regexp in `Mail::Utilites#dquote`? The warning polutes our tests output - no big deal - but why not to get rid of it completely..?

**Comment by jeremy** [comment]
`/n` means an ASCII-8BIT match instead of using the source encoding. Looking at the git history, it may have been used to avoid issues matching SJIS strings with a UTF-8 regexp, but hard to say. All the other regexps added since then (and some regexps that existed back then) used the source encoding.

So, there's no issue or bug here, but we can safely remove it for 2.7.0.

Could you get rid of it and submit a PR?
