### ISSUE TITLE
How to escape double quote in From header?

### ISSUE THREAD

**Issue by dalibor** [mikel/mail#929]
How would you escape double quote in `From` header? Say I want to have a From header like:

``` ruby
From: "Fred \"The Hammer\" Williamson" <fred@example.com>
```

Trying the following, the double quote escape `\"` gets escaped as `\\\"`:

``` ruby
puts Mail::FromField.new('"Fred \"The Hammer\" Williamson" <user@example.com>')
"Fred \\\"The Hammer\\\" Williamson" <fred@example.com>
```

p.s. The From name wrapping quotes are needed for the case when there is comma in the name.

**Comment by yukideluxe** [comment]
I'd like to raise awareness about this issue because I am facing the same situation. If you already send a proper escaped address in the `From` field (also `Reply-To` and other address fields) it gets double escaped here 
https://github.com/mikel/mail/blob/master/lib/mail/elements/address_list.rb#L29
which is called from
https://github.com/mikel/mail/blob/master/lib/mail/fields/common/common_address.rb#L104

I am not sure how we can avoid this situation because sending not proper escaped values in the `From` field could raise `ParseError` when building the message.

Any ideas?
