### ISSUE TITLE
Email address parser

### ISSUE THREAD

**Issue by mariokostelac** [mikel/mail#968]
I've been using mail gem for parsing email addresses quite heavily and I've noticed that some real-world addresses can't be parsed.
One example would be `Kostelac, Mario <mario@example.com>`. I know it is not a valid one, but it is really obvious for a human person how it should be parsed. I've been digging into address lists parsing machine and I've realised it's not 100% copy of grammar defined on https://www.ietf.org/rfc/rfc2822.txt.
One example would be `obs_phrase` defined on https://github.com/mikel/mail/blob/f0efbd4850d1bc06cdcba6178c282eeaba9c8c43/lib/mail/parsers/ragel/common.rl#L49 (the original one does not contain `@`).

My general question is what is general attitude about this gem. Should it be something that strictly follows the standard and does not go further or it should be as useful as possible for building reliable services that deal with emails.
If the latter one is the answer, I am happy to cover address list parser with more tests and then add parsing for some new address forms.

Also, one trivial example that happens is `"Mario Kostelac" <mario@example.com>>`.

**Comment by scsmith** [comment]
I can't answer the question but I'd like to add another example of something similar. We've seen an email that contains:

```
Keywords: {"Key":"Value"}
```

Technically this breaks the parser because it's not a valid PhraseList. Is this something that should operate according to the spec verbatim (which will discount a large proportion of real-world messages) or should the parse fall back to allowing a generic string?

**Comment by jeremy** [comment]
Liberal in what we accept, strict in what we generate. Happy to see PRs with looser parsing, so long as it doesn't compromise legit common-case parsing or overly complicate the code.
